syntax = "proto3";

package mentor.types.identity;

import "google/protobuf/timestamp.proto";

// Обогащенный профиль пользователя (составной ответ API).
message UserProfile {
  // Данные из внешней системы (Real-time sync).
  PublicUserProfile public_profile = 1;

  // Язык коммуникации с ботами (en, ru).
  Locale interface_language = 2;
}

// Публичный профиль пользователя.
message PublicUserProfile {
  uint32 distributor_id = 1;    // ID пригласителя (u32).
  string distributor_login = 2; // Логин пригласителя.
  string referral_link = 3;     // Реферальная ссылка самого пользователя.

  // Telegram ID.
  int64 telegram_id = 4; 
  string telegram_username = 5; // "durov"

  string first_name = 6;
  string last_name = 7;
  string avatar_url = 8; // Аватарка.
  
  google.protobuf.Timestamp created_at = 9;
}

// Локаль - поддерживаемый язык.
message Locale {
  message Id {
      string code = 1; // "ru", "en"
  }
  
  string code = 1; // "ru", "en"
  string display_name = 2; // "Русский"
}

// Валюта (Справочник).
message Currency {
  message Id {
    string code = 1; // "TON"
  }
  
  string code = 1;         // TON, USDT
  string display_name = 2; // "Toncoin"
  string symbol = 3;       // $, 💎
  int32 decimals = 4;      // Кол-во знаков после запятой (9 для TON)
}

// Валютная пара (Конфигурация).
// Определяет, какие пары доступны для обмена/отображения.
message ExchangePair {
  message Id {
      string pair_id = 1; // "TON/USD"
  }

  // Список идентификаторов валютных пар.
  // Используется в запросах на подписку.
  message List {
      repeated string pair_ids = 1;
  }

  string pair_id = 1; // "TON/USD"

  string base_currency_code = 2;  // "TON" (Товар)
  string quote_currency_code = 3; // "USD" (Цена)
}

// Текущий курс обмена (Real-time данные).
message ExchangeRate {
  string pair_id = 1; // "TON/USD"
  
  string buy_rate = 2;  // Курс покупки (сколько quote платим за 1 base) "5.50"
  string sell_rate = 3; // Курс продажи (сколько quote получаем за 1 base) "5.45"
  
  google.protobuf.Timestamp updated_at = 4;
}

// Системная конфигурация.
// Содержит все справочники необходимые для старта приложения.
message SystemConfig {
  repeated Locale locales = 1;
  
  // Доступные валюты (Справочник).
  repeated Currency currencies = 2;
  
  // Доступные валютные пары.
  repeated ExchangePair exchange_pairs = 3;
  
  // Актуальные курсы (Snapshot на момент запроса).
  repeated ExchangeRate exchange_rates = 4;
}
