syntax = "proto3";

package mentor.admin.bot;

import "google/protobuf/empty.proto";
import "mentor/types/bot.proto";
import "mentor/types/billing.proto";

// Админ-сервис управления ботами.
service BotAdminService {
    rpc CreateBot(CreateBotRequest) returns (CreateBotResponse);
    rpc UpdateBot(UpdateBotRequest) returns (UpdateBotResponse);
    rpc DeleteBot(mentor.types.bot.Bot.Id) returns (google.protobuf.Empty);
    rpc ListBots(ListBotsRequest) returns (ListBotsResponse);

    // Управление тарифами бота.
    rpc CreatePricingPlan(CreatePricingPlanRequest) returns (CreatePricingPlanResponse);
    rpc UpdatePricingPlan(UpdatePricingPlanRequest) returns (UpdatePricingPlanResponse);
}

message CreateBotRequest {
    mentor.types.bot.Bot bot = 1;
}

message CreateBotResponse {
    mentor.types.bot.Bot bot = 1;
}

message UpdateBotRequest {
    mentor.types.bot.Bot bot = 1;
}

message UpdateBotResponse {
    mentor.types.bot.Bot bot = 1;
}


message ListBotsRequest {
    int32 page_size = 1;
    string page_token = 2;
}

message ListBotsResponse {
    repeated mentor.types.bot.Bot items = 1;
    string next_page_token = 2;
}

message CreatePricingPlanRequest {
    mentor.types.billing.BotTariffPlan plan = 1;
}

message CreatePricingPlanResponse {
    mentor.types.billing.BotTariffPlan plan = 1;
}

message UpdatePricingPlanRequest {
    mentor.types.billing.BotTariffPlan plan = 1;
}

message UpdatePricingPlanResponse {
    mentor.types.billing.BotTariffPlan plan = 1;
}
